export const COMMON_TRAVEL_TIME_ZONES = [
  "UTC",
  "Asia/Kolkata",
  "Asia/Colombo",
  "Asia/Kathmandu",
  "Asia/Dubai",
  "Asia/Riyadh",
  "Asia/Maldives",
  "Asia/Bangkok",
  "Asia/Singapore",
  "Asia/Kuala_Lumpur",
  "Asia/Hong_Kong",
  "Asia/Tokyo",
  "Asia/Seoul",
  "Europe/London",
  "Europe/Paris",
  "Europe/Rome",
  "Europe/Zurich",
  "Europe/Istanbul",
  "Africa/Cairo",
  "Africa/Nairobi",
  "Indian/Mauritius",
  "Australia/Sydney",
  "Pacific/Auckland",
  "America/New_York",
  "America/Toronto",
  "America/Los_Angeles",
] as const;
