-- Phase 7 / Phase 16: human-reviewed traveler entry readiness.
--
-- This deliberately stores no passport number, identity-document image, or
-- immigration conclusion generated by AI. Operators record only the minimum
-- structured dates/country codes needed to route internal risk. Visa
-- requirements other than "unknown" require a human-provided evidence label.

alter table public.travelers
  add constraint travelers_organization_trip_id_key
  unique (organization_id, trip_id, id);

create table public.traveler_entry_checks (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null,
  trip_id uuid not null,
  traveler_id uuid not null,
  destination_country_code text not null
    check (destination_country_code ~ '^[A-Z]{2}$'),
  citizenship_country_code text not null
    check (citizenship_country_code ~ '^[A-Z]{2}$'),
  passport_issuing_country_code text
    check (
      passport_issuing_country_code is null
      or passport_issuing_country_code ~ '^[A-Z]{2}$'
    ),
  passport_expires_on date,
  passport_validity_months_required smallint not null default 6
    check (passport_validity_months_required between 0 and 12),
  visa_requirement text not null default 'unknown'
    check (
      visa_requirement in (
        'unknown',
        'not_required',
        'required',
        'conditional'
      )
    ),
  visa_status text not null default 'unknown'
    check (
      visa_status in (
        'unknown',
        'not_applicable',
        'researching',
        'application_pending',
        'granted',
        'refused'
      )
    ),
  visa_valid_until date,
  action_due_on date,
  evidence_source_label text
    check (
      evidence_source_label is null
      or char_length(evidence_source_label) between 2 and 180
    ),
  evidence_source_url text
    check (
      evidence_source_url is null
      or (
        char_length(evidence_source_url) <= 1_000
        and evidence_source_url ~ '^https://'
      )
    ),
  reviewed_by uuid,
  reviewed_at timestamptz not null default statement_timestamp(),
  created_at timestamptz not null default statement_timestamp(),
  updated_at timestamptz not null default statement_timestamp(),
  constraint traveler_entry_checks_organization_id_id_key
    unique (organization_id, id),
  constraint traveler_entry_checks_traveler_destination_key
    unique (
      organization_id,
      traveler_id,
      destination_country_code
    ),
  constraint traveler_entry_checks_traveler_same_trip_fkey
    foreign key (organization_id, trip_id, traveler_id)
    references public.travelers (organization_id, trip_id, id)
    on delete cascade,
  constraint traveler_entry_checks_reviewer_same_organization_fkey
    foreign key (organization_id, reviewed_by)
    references public.memberships (organization_id, user_id)
    on delete set null (reviewed_by),
  constraint traveler_entry_checks_requirement_evidence_check
    check (
      visa_requirement = 'unknown'
      or evidence_source_label is not null
    ),
  constraint traveler_entry_checks_visa_state_check
    check (
      (visa_requirement = 'not_required'
        and visa_status = 'not_applicable')
      or
      (visa_requirement in ('required', 'conditional')
        and visa_status <> 'not_applicable')
      or
      (visa_requirement = 'unknown'
        and visa_status in ('unknown', 'researching'))
    )
);

create index traveler_entry_checks_trip_idx
  on public.traveler_entry_checks (
    organization_id,
    trip_id,
    destination_country_code
  );
create index traveler_entry_checks_passport_expiry_idx
  on public.traveler_entry_checks (
    organization_id,
    passport_expires_on
  )
  where passport_expires_on is not null;
create index traveler_entry_checks_action_due_idx
  on public.traveler_entry_checks (
    organization_id,
    action_due_on
  )
  where action_due_on is not null
    and visa_status not in ('granted', 'not_applicable');
create index traveler_entry_checks_reviewer_idx
  on public.traveler_entry_checks (reviewed_by);

create trigger traveler_entry_checks_set_updated_at
  before update on public.traveler_entry_checks
  for each row execute function public.set_updated_at();
create trigger traveler_entry_checks_prevent_organization_move
  before update on public.traveler_entry_checks
  for each row execute function private.prevent_organization_id_change();

alter table public.traveler_entry_checks enable row level security;

create policy traveler_entry_checks_member_select
  on public.traveler_entry_checks
  for select
  to authenticated
  using (
    public.meets_mfa_requirement()
    and public.is_active_member(organization_id)
  );

revoke all on table public.traveler_entry_checks
  from public, anon, authenticated;
grant select on table public.traveler_entry_checks to authenticated;
grant select, insert, update, delete
  on table public.traveler_entry_checks to service_role;

create or replace function public.upsert_traveler_entry_check(
  target_organization_id uuid,
  target_trip_id uuid,
  target_traveler_id uuid,
  target_destination_country_code text,
  target_citizenship_country_code text,
  target_passport_issuing_country_code text default null,
  target_passport_expires_on date default null,
  target_passport_validity_months_required smallint default 6,
  target_visa_requirement text default 'unknown',
  target_visa_status text default 'unknown',
  target_visa_valid_until date default null,
  target_action_due_on date default null,
  target_evidence_source_label text default null,
  target_evidence_source_url text default null
)
returns setof public.traveler_entry_checks
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  actor_id uuid := (select auth.uid());
  destination_code text := upper(trim(target_destination_country_code));
  citizenship_code text := upper(trim(target_citizenship_country_code));
  passport_country_code text :=
    nullif(upper(trim(target_passport_issuing_country_code)), '');
  evidence_label text := nullif(trim(target_evidence_source_label), '');
  evidence_url text := nullif(trim(target_evidence_source_url), '');
  current_check public.traveler_entry_checks%rowtype;
  changed_at timestamptz := statement_timestamp();
begin
  if actor_id is null
    or not public.meets_mfa_requirement()
    or not public.has_organization_role(
      target_organization_id,
      array[
        'owner',
        'admin',
        'trip_designer',
        'operations',
        'agent'
      ]::public.app_role[]
    )
  then
    raise exception 'You do not have permission to review traveler entry readiness.'
      using errcode = '42501';
  end if;

  if destination_code !~ '^[A-Z]{2}$'
    or citizenship_code !~ '^[A-Z]{2}$'
    or (
      passport_country_code is not null
      and passport_country_code !~ '^[A-Z]{2}$'
    )
  then
    raise exception 'Use two-letter ISO country codes for entry readiness.'
      using errcode = '22023';
  end if;

  if target_passport_validity_months_required not between 0 and 12 then
    raise exception 'Passport validity must be between zero and twelve months.'
      using errcode = '22023';
  end if;

  if target_visa_requirement not in (
    'unknown',
    'not_required',
    'required',
    'conditional'
  )
    or target_visa_status not in (
      'unknown',
      'not_applicable',
      'researching',
      'application_pending',
      'granted',
      'refused'
    )
  then
    raise exception 'The traveler entry-readiness state is not supported.'
      using errcode = '22023';
  end if;

  if target_visa_requirement <> 'unknown'
    and evidence_label is null
  then
    raise exception 'Record the human-reviewed visa evidence source.'
      using errcode = '22023';
  end if;

  if evidence_url is not null
    and (
      char_length(evidence_url) > 1_000
      or evidence_url !~ '^https://'
    )
  then
    raise exception 'The evidence link must use HTTPS.'
      using errcode = '22023';
  end if;

  if not (
    (target_visa_requirement = 'not_required'
      and target_visa_status = 'not_applicable')
    or
    (target_visa_requirement in ('required', 'conditional')
      and target_visa_status <> 'not_applicable')
    or
    (target_visa_requirement = 'unknown'
      and target_visa_status in ('unknown', 'researching'))
  )
  then
    raise exception 'The visa requirement and workflow state do not agree.'
      using errcode = '22023';
  end if;

  perform 1
  from public.travelers traveler
  where traveler.organization_id = target_organization_id
    and traveler.trip_id = target_trip_id
    and traveler.id = target_traveler_id
  for update;

  if not found then
    raise exception 'This traveler is not available on the selected trip.'
      using errcode = '42501';
  end if;

  insert into public.traveler_entry_checks as entry_check (
    organization_id,
    trip_id,
    traveler_id,
    destination_country_code,
    citizenship_country_code,
    passport_issuing_country_code,
    passport_expires_on,
    passport_validity_months_required,
    visa_requirement,
    visa_status,
    visa_valid_until,
    action_due_on,
    evidence_source_label,
    evidence_source_url,
    reviewed_by,
    reviewed_at
  )
  values (
    target_organization_id,
    target_trip_id,
    target_traveler_id,
    destination_code,
    citizenship_code,
    passport_country_code,
    target_passport_expires_on,
    target_passport_validity_months_required,
    target_visa_requirement,
    target_visa_status,
    target_visa_valid_until,
    target_action_due_on,
    evidence_label,
    evidence_url,
    actor_id,
    changed_at
  )
  on conflict (
    organization_id,
    traveler_id,
    destination_country_code
  )
  do update set
    citizenship_country_code = excluded.citizenship_country_code,
    passport_issuing_country_code =
      excluded.passport_issuing_country_code,
    passport_expires_on = excluded.passport_expires_on,
    passport_validity_months_required =
      excluded.passport_validity_months_required,
    visa_requirement = excluded.visa_requirement,
    visa_status = excluded.visa_status,
    visa_valid_until = excluded.visa_valid_until,
    action_due_on = excluded.action_due_on,
    evidence_source_label = excluded.evidence_source_label,
    evidence_source_url = excluded.evidence_source_url,
    reviewed_by = excluded.reviewed_by,
    reviewed_at = excluded.reviewed_at
  returning entry_check.*
  into current_check;

  insert into public.audit_events (
    organization_id,
    actor_id,
    event_type,
    entity_type,
    entity_id,
    metadata,
    created_at
  )
  values (
    target_organization_id,
    actor_id,
    'record.updated',
    'traveler_entry_check',
    current_check.id,
    jsonb_build_object(
      'event', 'trip.traveler_entry_readiness_reviewed',
      'trip_id', target_trip_id,
      'traveler_id', target_traveler_id,
      'destination_country_code', destination_code,
      'visa_requirement', target_visa_requirement,
      'visa_status', target_visa_status,
      'has_passport_expiry', target_passport_expires_on is not null,
      'has_evidence_url', evidence_url is not null
    ),
    changed_at
  );

  return next current_check;
end;
$$;

revoke all on function public.upsert_traveler_entry_check(
  uuid,
  uuid,
  uuid,
  text,
  text,
  text,
  date,
  smallint,
  text,
  text,
  date,
  date,
  text,
  text
)
  from public, anon;
grant execute on function public.upsert_traveler_entry_check(
  uuid,
  uuid,
  uuid,
  text,
  text,
  text,
  date,
  smallint,
  text,
  text,
  date,
  date,
  text,
  text
)
  to authenticated;

-- Add four objective, internal-only readiness signals. The existing detector
-- remains the tested lower layer; this wrapper does not contact external
-- services or make an immigration decision.
alter function private.find_operational_exceptions(uuid)
  rename to find_operational_exceptions_v3;

alter table public.operational_exceptions
  drop constraint operational_exceptions_exception_type_check,
  add constraint operational_exceptions_exception_type_check
    check (
      exception_type in (
        'trip_dates_missing',
        'traveler_roster_empty',
        'booking_plan_empty',
        'booking_schedule_missing',
        'booking_confirmation_at_risk',
        'document_expiring',
        'operational_task_overdue',
        'payment_due',
        'traveler_entry_review_missing',
        'traveler_passport_at_risk',
        'traveler_visa_at_risk',
        'itinerary_readiness_at_risk'
      )
    ),
  drop constraint operational_exceptions_source_entity_type_check,
  add constraint operational_exceptions_source_entity_type_check
    check (
      source_entity_type in (
        'trip',
        'traveler',
        'traveler_entry_check',
        'booking',
        'document',
        'task',
        'payment'
      )
    );

create or replace function private.find_operational_exceptions(
  target_organization_id uuid
)
returns table (
  finding_dedupe_key text,
  finding_trip_id uuid,
  finding_exception_type text,
  finding_severity text,
  finding_source_entity_type text,
  finding_source_entity_id uuid,
  finding_title text,
  finding_summary text,
  finding_evidence jsonb,
  finding_due_at timestamptz,
  finding_assigned_to uuid
)
language sql
stable
set search_path = pg_catalog, public, private
as $$
  select *
  from private.find_operational_exceptions_v3(target_organization_id)

  union all

  select
    format('traveler:%s:entry-review', traveler.id),
    trip.id,
    'traveler_entry_review_missing',
    case
      when trip.status = 'in_travel'
        or trip.start_date <= current_date + 7
        then 'critical'
      when trip.start_date <= current_date + 30 then 'high'
      else 'medium'
    end,
    'traveler',
    traveler.id,
    'Traveller entry-readiness review is missing',
    format(
      '%s %s has no human-reviewed passport and visa readiness record.',
      traveler.first_name,
      coalesce(traveler.last_name, '')
    ),
    jsonb_build_object(
      'traveler_id', traveler.id,
      'trip_start_date', trip.start_date
    ),
    (trip.start_date - 30)::timestamp at time zone 'UTC',
    trip.owner_id
  from public.travelers traveler
  join public.trips trip
    on trip.organization_id = traveler.organization_id
   and trip.id = traveler.trip_id
  where traveler.organization_id = target_organization_id
    and trip.status in ('confirmed', 'in_travel')
    and trip.start_date is not null
    and not exists (
      select 1
      from public.traveler_entry_checks entry_check
      where entry_check.organization_id = traveler.organization_id
        and entry_check.trip_id = traveler.trip_id
        and entry_check.traveler_id = traveler.id
    )

  union all

  select
    format('entry-check:%s:passport', entry_check.id),
    trip.id,
    'traveler_passport_at_risk',
    case
      when trip.status = 'in_travel'
        or (
          entry_check.passport_expires_on is not null
          and entry_check.passport_expires_on < trip.end_date
        )
        then 'critical'
      when trip.start_date <= current_date + 30 then 'high'
      else 'medium'
    end,
    'traveler_entry_check',
    entry_check.id,
    case
      when entry_check.passport_expires_on is null
        then 'Passport expiry evidence is missing'
      else 'Passport validity needs review'
    end,
    format(
      '%s %s needs passport validity evidence for %s before this trip.',
      traveler.first_name,
      coalesce(traveler.last_name, ''),
      entry_check.destination_country_code
    ),
    jsonb_build_object(
      'traveler_id', traveler.id,
      'destination_country_code',
      entry_check.destination_country_code,
      'passport_expires_on', entry_check.passport_expires_on,
      'passport_validity_months_required',
      entry_check.passport_validity_months_required,
      'trip_end_date', trip.end_date
    ),
    (trip.start_date - 30)::timestamp at time zone 'UTC',
    trip.owner_id
  from public.traveler_entry_checks entry_check
  join public.travelers traveler
    on traveler.organization_id = entry_check.organization_id
   and traveler.trip_id = entry_check.trip_id
   and traveler.id = entry_check.traveler_id
  join public.trips trip
    on trip.organization_id = entry_check.organization_id
   and trip.id = entry_check.trip_id
  where entry_check.organization_id = target_organization_id
    and trip.status in ('confirmed', 'in_travel')
    and trip.start_date is not null
    and trip.end_date is not null
    and (
      entry_check.passport_expires_on is null
      or entry_check.passport_expires_on
        < (
          trip.end_date
          + make_interval(
              months => entry_check.passport_validity_months_required
            )
        )::date
    )

  union all

  select
    format('entry-check:%s:visa', entry_check.id),
    trip.id,
    'traveler_visa_at_risk',
    case
      when trip.status = 'in_travel'
        or entry_check.visa_status = 'refused'
        or coalesce(
          entry_check.action_due_on,
          trip.start_date - 30
        ) < current_date
        or trip.start_date <= current_date + 7
        then 'critical'
      when trip.start_date <= current_date + 30 then 'high'
      else 'medium'
    end,
    'traveler_entry_check',
    entry_check.id,
    'Visa readiness needs human action',
    format(
      '%s %s is %s for %s; the reviewed requirement is %s.',
      traveler.first_name,
      coalesce(traveler.last_name, ''),
      replace(entry_check.visa_status, '_', ' '),
      entry_check.destination_country_code,
      replace(entry_check.visa_requirement, '_', ' ')
    ),
    jsonb_build_object(
      'traveler_id', traveler.id,
      'destination_country_code',
      entry_check.destination_country_code,
      'visa_requirement', entry_check.visa_requirement,
      'visa_status', entry_check.visa_status,
      'visa_valid_until', entry_check.visa_valid_until,
      'action_due_on', entry_check.action_due_on,
      'evidence_source_label', entry_check.evidence_source_label
    ),
    coalesce(
      entry_check.action_due_on,
      trip.start_date - 30
    )::timestamp at time zone 'UTC',
    trip.owner_id
  from public.traveler_entry_checks entry_check
  join public.travelers traveler
    on traveler.organization_id = entry_check.organization_id
   and traveler.trip_id = entry_check.trip_id
   and traveler.id = entry_check.traveler_id
  join public.trips trip
    on trip.organization_id = entry_check.organization_id
   and trip.id = entry_check.trip_id
  where entry_check.organization_id = target_organization_id
    and trip.status in ('confirmed', 'in_travel')
    and trip.start_date is not null
    and entry_check.visa_requirement in ('required', 'conditional')
    and (
      entry_check.visa_status <> 'granted'
      or (
        entry_check.visa_valid_until is not null
        and trip.end_date is not null
        and entry_check.visa_valid_until < trip.end_date
      )
    )

  union all

  select
    format('trip:%s:itinerary-readiness', trip.id),
    trip.id,
    'itinerary_readiness_at_risk',
    case
      when trip.status = 'in_travel'
        or trip.start_date - 14 < current_date
        then 'critical'
      when trip.start_date <= current_date + 30 then 'high'
      else 'medium'
    end,
    'trip',
    trip.id,
    case
      when itinerary.covered_days = 0 then 'Operational itinerary is missing'
      else 'Operational itinerary has uncovered days'
    end,
    format(
      '%s covers %s of %s trip days in the internal itinerary.',
      trip.name,
      itinerary.covered_days,
      (trip.end_date - trip.start_date + 1)
    ),
    jsonb_build_object(
      'trip_start_date', trip.start_date,
      'trip_end_date', trip.end_date,
      'covered_days', itinerary.covered_days,
      'expected_days', trip.end_date - trip.start_date + 1
    ),
    (trip.start_date - 14)::timestamp at time zone 'UTC',
    trip.owner_id
  from public.trips trip
  cross join lateral (
    select count(distinct item.day_number)::integer as covered_days
    from public.itinerary_items item
    where item.organization_id = trip.organization_id
      and item.trip_id = trip.id
      and item.day_number
        between 1 and (trip.end_date - trip.start_date + 1)
  ) itinerary
  where trip.organization_id = target_organization_id
    and trip.status in ('confirmed', 'in_travel')
    and trip.start_date is not null
    and trip.end_date is not null
    and itinerary.covered_days < (trip.end_date - trip.start_date + 1);
$$;

revoke all on function private.find_operational_exceptions_v3(uuid)
  from public, anon, authenticated;
revoke all on function private.find_operational_exceptions(uuid)
  from public, anon, authenticated;

-- Keep detector version evidence aligned with the new rules while preserving
-- the existing actor/service authorization and deterministic reconcile path.
create or replace function public.refresh_operational_exceptions(
  target_organization_id uuid
)
returns table (
  active_count bigint,
  critical_count bigint,
  resolved_count integer,
  scanned_at timestamptz
)
language plpgsql
security definer
set search_path = pg_catalog, public, private
as $$
declare
  actor_id uuid := (select auth.uid());
  is_service_worker boolean :=
    coalesce((select auth.role()) = 'service_role', false);
  scan_time timestamptz := statement_timestamp();
  cleared_count integer := 0;
begin
  if not is_service_worker and (
    actor_id is null
    or not public.meets_mfa_requirement()
    or not public.has_organization_role(
      target_organization_id,
      array[
        'owner',
        'admin',
        'trip_designer',
        'operations',
        'finance'
      ]::public.app_role[]
    )
  )
  then
    raise exception 'You do not have permission to refresh Operations Radar.'
      using errcode = '42501';
  end if;

  insert into public.operational_exceptions as exception (
    organization_id,
    trip_id,
    dedupe_key,
    exception_type,
    severity,
    status,
    source_entity_type,
    source_entity_id,
    title,
    summary,
    evidence,
    due_at,
    assigned_to,
    detected_by,
    detected_at,
    last_seen_at,
    acknowledged_by,
    acknowledged_at,
    resolved_by,
    resolved_at,
    operator_note
  )
  select
    target_organization_id,
    finding.finding_trip_id,
    finding.finding_dedupe_key,
    finding.finding_exception_type,
    finding.finding_severity,
    'open',
    finding.finding_source_entity_type,
    finding.finding_source_entity_id,
    finding.finding_title,
    finding.finding_summary,
    finding.finding_evidence,
    finding.finding_due_at,
    finding.finding_assigned_to,
    'rules_engine',
    scan_time,
    scan_time,
    null,
    null,
    null,
    null,
    null
  from private.find_operational_exceptions(
    target_organization_id
  ) finding
  on conflict (organization_id, dedupe_key) do update
  set
    trip_id = excluded.trip_id,
    exception_type = excluded.exception_type,
    severity = excluded.severity,
    source_entity_type = excluded.source_entity_type,
    source_entity_id = excluded.source_entity_id,
    title = excluded.title,
    summary = excluded.summary,
    evidence = excluded.evidence,
    due_at = excluded.due_at,
    assigned_to = excluded.assigned_to,
    detected_by = excluded.detected_by,
    last_seen_at = excluded.last_seen_at,
    status = case
      when exception.status = 'resolved' then 'open'
      else exception.status
    end,
    acknowledged_by = case
      when exception.status = 'resolved' then null
      else exception.acknowledged_by
    end,
    acknowledged_at = case
      when exception.status = 'resolved' then null
      else exception.acknowledged_at
    end,
    resolved_by = null,
    resolved_at = null,
    operator_note = case
      when exception.status = 'resolved' then null
      else exception.operator_note
    end;

  update public.operational_exceptions exception
  set
    status = 'resolved',
    resolved_by = null,
    resolved_at = scan_time,
    operator_note = 'Condition cleared by Operations Radar.'
  where exception.organization_id = target_organization_id
    and exception.detected_by = 'rules_engine'
    and exception.status in ('open', 'acknowledged')
    and not exists (
      select 1
      from private.find_operational_exceptions(
        target_organization_id
      ) finding
      where finding.finding_dedupe_key = exception.dedupe_key
    );
  get diagnostics cleared_count = row_count;

  insert into public.audit_events (
    organization_id,
    actor_id,
    event_type,
    entity_type,
    metadata,
    created_at
  )
  values (
    target_organization_id,
    actor_id,
    'ai.tool_called',
    'operations_radar',
    jsonb_build_object(
      'event', 'trip.operations_radar_refreshed',
      'trigger', case
        when is_service_worker then 'durable_worker'
        else 'operator'
      end,
      'resolved_count', cleared_count,
      'detector_version', '2026.07.29.3'
    ),
    scan_time
  );

  return query
  select
    count(*) filter (
      where exception.status in ('open', 'acknowledged')
    ),
    count(*) filter (
      where exception.status in ('open', 'acknowledged')
        and exception.severity = 'critical'
    ),
    cleared_count,
    scan_time
  from public.operational_exceptions exception
  where exception.organization_id = target_organization_id;
end;
$$;

revoke all on function public.refresh_operational_exceptions(uuid)
  from public, anon;
grant execute on function public.refresh_operational_exceptions(uuid)
  to authenticated, service_role;
